name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 14.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Install
        run: npm install

      - name: Install Examples
        run: npm run install:examples

      - name: ⓘ Debug next-i18next installation
        shell: bash
        run: npx envinfo --binaries --npmPackages

      - name: ⓘ Debug examples/simple installation
        shell: bash
        working-directory: ./examples/simple
        run: npx envinfo --binaries --npmPackages

      - name: ESLint checks
        run: npm run lint

      - name: Build next-i18next
        run: npm run build

      - name: Build examples
        run: npm run build:examples

      - name: Check size limits
        run: npm run check-size

      - name: Check dist for ecmascript compliance
        run: npm run check-dist

      - name: Unit tests
        run: npm test

      # As the examples aren't part (yet) on the monorepo, they install the
      # latest published version of next-i18next, not the repo one (git). This will
      # be fixed soon. But in the meantime let's reproduce the strategy used
      # in the existing `example:simple` script. Warning it does not fully work.
      # We need a monorepo (either file:, workspace:...) for that.
      - name: E2E tests
        shell: bash
        run:
          - cp package.json examples/simple/node_modules/next-i18next/package.json
          - cp -r dist examples/simple/node_modules/next-i18next
          - cp package.json examples/ssg/node_modules/next-i18next/package.json
          - cp -r dist examples/ssg/node_modules/next-i18next
          - npm run test:e2e

      - name: Build example with experimental.esmExternals
        run: npm run build:example:simple
        env:
          NEXTJS_ESM_EXTERNALS: true
